### ISSUE TITLE
Pages not regenerating

### ISSUE THREAD

**Issue by hamishtaplin** [emadalam/atvjs#2]
Came across [this comment on SO](http://stackoverflow.com/questions/33532217/force-view-to-reload-tvml-content-on-apple-tv-tvos) indicating that pages would regenerate when you navigate to them. 

This doesn't seem to be the case for me at the moment, are changes to the template supposed to be available without rebooting the application?

**Comment by emadalam** [comment]
@hamishtaplin Can you please describe your complete usecase?

The pages are dynamically created based on the provided template and the url. If your template and data are the same, even if the pages are dynamically created, you'd not see any difference. Either your data needs to change (the server should return fresh data) or you can change your template in realtime if you wish to, and you would see the changes when you navigate to your page. Use `ready(options, resolve, reject)` configuration if you want to change your template based on your app logic. However, this would not be a good practice. In real world, you should create different pages that maps to different unique templates and only your data should change in realtime.

Let me give you a simple example. Imagine a movie details page in your application.

```javascript
// Movie Details page
ATV.Page.create({
	name: 'movie',
	template: your_movie_detail_template,
	// catch any extra details to populate the page
	ready(options, resolve, reject) {
		let movieId = options.id;

		// get data for the specific movie using ajax
		ATV
			.Ajax
			.get(`https://path/to/your/movie/json/${movieId}`)
			.then((xhr) => {
				let response = xhr.response;
				resolve(response);
			}, (xhr) => {
				// some error handling or call the default error handler
				// calling reject is not preferred but you may do so
				reject(xhr);
			});
	}
});

// somewhere in your application
ATV.Navigation.navigate('movie', {id: 'some_movie_id'});

// or you may define something like below in some other templates
// <lockup data-href-page="movie" data-href-page-options='{"id": "some_movie_id"}'>
// 		<!-- usual tvml -->
// </lockup>
```
Above example lets you have a single dynamic page which is populated with different set of data each time you navigate to the page with a different movie id.

**Comment by hamishtaplin** [comment]
My use case is simply that, upon editing a template, I have to re-build the whole app before the changes are reflected in the simulator. Just changing the template and then navigating to it does not reflect those changes.

**Comment by emadalam** [comment]
The templates and every other logic is part of your application JavaScript code. Once you load the final version of your application JS into the tvOS application context, the same code is run in its entirety throughout the application lifespan. If you make a new version of your application JS, it's quite logical and obvious that your application must quit and restart to load the new version of your JS code. To give you an example, let's assume that you load a webpage into your browser. Once you do so, the browser loads the related assets plus your application JS into the browser context and the same JS is run in it's entirety until the webpage is open. Now let's assume you change some JS code in your server. Does the webpage automatically reload the new JS code that you updated at your server. NO. It will only do so when you refresh the page (similar to reloading the application) and the browser will then pull the updated version of your application JS.

What you're asking for has nothing to do with page regeneration.
