### ISSUE TITLE
Create common aliases

### ISSUE THREAD

**Issue by emadalam** [emadalam/atvjs#29]
Currently
---
The commonly used methods are under a second level object.

Wanted
---
Create aliases
- [ ] `ATV.Page.create` --> `ATV.createPage`
- [ ] `ATV.Menu.create` --> `ATV.createMenu`
- [ ] `ATV.Navigation.navigate` --> `ATV.navigateTo`
- [ ] `ATV.Navigation.navigateToMenuPage` --> `ATV.navigateToMenuPage`
- [ ] `ATV.Navigation.presentModal` --> `ATV.presentModal`
- [ ] `ATV.Navigation.dismissModal` --> `ATV.dismissModal`

**Comment by Sharan-ram** [comment]
@emadalam , is the issue still open? i'm new t open source,would like to work on it
