### ISSUE TITLE
how can I get from catalog view to product view

### ISSUE THREAD

**Issue by andreschmid98** [emadalam/atvjs#31]
I want when I click on a thumbnail in the catalogue view to the product view to play the video of the thumbnail.

I get thumbnail and video from a json file. 
and this is my catalog index.js file:
```
let Page = ATV.Page.create({
	name: 'catalog',
	url: 'http://localhost:9001/assets/data/video.json',
	template: template,
    events: {
        select: 'onSelect'
    },

	onSelect(e) {
		ATV.Navigation.navigate('product');
	}
});
```

And I don't know how I can play the video when I get to the product(video) view.

**Comment by emadalam** [comment]
Have you seen the below boilerplate and the fully functional demo app. It has all the basic samples including the movie catalog using real APIs and a player with sample hls streams.

https://github.com/emadalam/appletv-demo
https://github.com/emadalam/appletv-boilerplate
