### ISSUE TITLE
Sample code for player

### ISSUE THREAD

**Issue by phanisaripalli** [emadalam/atvjs#42]
Hello. Could you please provide a sample code for initializing the player and playing the actual movie. 

Thank you.

**Comment by emadalam** [comment]
Did you happen to check the demo repo https://github.com/emadalam/appletv-demo which has the player example?

You can create a generic `Play` page that plays any url passed to it. Something like here, https://github.com/emadalam/appletv-demo/blob/master/web/app/pages/play/index.js could be created. Note, though the urls are hardcoded in the above example, you can receive those as `options` passed to the page https://github.com/emadalam/appletv-demo/blob/master/web/app/pages/movie-details/template.hbs#L17.

Does this work for you? Or you need more examples?

**Comment by phanisaripalli** [comment]
@emadalam sorry for not following up. Yes, I found what I was looking for. Thank you very much
