### ISSUE TITLE
Small example project

### ISSUE THREAD

**Issue by jinpark** [emadalam/atvjs#5]
Just wondering if we could get a small example project here thats just a `menu` -> `catalog` -> `video play` without all the dependencies of  https://github.com/emadalam/tvml-catalog-using-atvjs . That project is awesome but for a small project, it requires karma, webpack, gulp, babel etc, which seems a bit overkill.

**Comment by spunkedy** [comment]
I created one here: 
https://github.com/spunkedy/simpleATVJS

This is not using webconf/webpacker to build a static site. This just serves up the static content. If you wanted to use UMD you would need to write your own based upon the referenced tvml catalog

**Comment by jinpark** [comment]
thanks a lot!
