### ISSUE TITLE
Need help, newbie here

### ISSUE THREAD

**Issue by MarcoGT** [emadalam/atvjs#53]
I am trying to develop an application using atvjs; installed node and npm; installed packages and so on. If in my app.js I do "import atvjs" is not working; also if I do "var atvjs = require('atvjs') is not working and I get "ReferenceError: Can't find variable: require"

Where am I wrong?

**Comment by emadalam** [comment]
@MarcoGT Have you checked the [samples](https://github.com/emadalam/atvjs#sample-code) and some [useful links](https://github.com/emadalam/atvjs#useful-links) to get you started? That would help 🙏

**Comment by MarcoGT** [comment]
Yes, but my main problem is the setup with Node/Gulp and so on where I am not an expert at all. I also downloaded your sample and try to run them but I also get an error when I do the first import from atvjs

**Comment by emadalam** [comment]
Please set up [node](https://nodejs.org/en/) in your machine and then follow the [getting started](https://github.com/emadalam/appletv-boilerplate#getting-started) section to run the server. You'd then be able to start the AppleTV app.

**Comment by MarcoGT** [comment]
Well, I did it, but the problem is when I start the Xcode App, I have error when I do “import” the external modules
Il 10 apr 2020, 12:10 +0200, Emad Alam <notifications@github.com>, ha scritto:

**Comment by emadalam** [comment]
Couple of things.

- Which external modules? Are those modules listed in `package.json` and installed using `npm install`?
- Is the build running? Have you tried `npm start` after doing `npm install`?
- Can you provide a sample repository where you face the problems?

I could only give you pointers regarding the issue that you might be facing. It has nothing to do with the library usage, you need to get yourself familiar with the node/npm ecosystem and the build processes. I would advise you to search the web for tutorials to get started with npm and webpack for web development and then follow along those guides and adapt as needed 🙏

**Comment by MarcoGT** [comment]
Well, the problem is immediately at the beginning, because after I download the sample app, I get error when I do “npm install” about webpack dependencies:

npm WARN uglifyjs-webpack-plugin@0.4.6 requires a peer of webpack@^1.9 || ^2 || ^2.1.0-beta || ^2.2.0-rc || ^3.0.0 but none is installed. You must install peer dependencies yourself.
Il 13 apr 2020, 20:09 +0200, Emad Alam <notifications@github.com>, ha scritto:

**Comment by emadalam** [comment]
At this point I'm afraid this conversation is not leading anywhere. I advise you to get yourself familiar with the node/npm/webpack setup and web development build process in general, and then revisit the app. There are a lot of tutorials out there that you can refer to get yourself up to speed.

The sample apps provided here have been used by many to get started without any issues. If you have framework specific questions, feel free to open an issue or search for existing closed issues here.
