### ISSUE TITLE
Pass options to page and display it

### ISSUE THREAD

**Issue by procom** [emadalam/atvjs#9]
Hello,

I would like to pass options to a page with `data-href-page-options`.
`<button data-href-page="details-page" data-href-page-options='{"title": "Hello World"}'>`

 /details-page/index.js : 
```
ATV.Page.create({
    name: 'DetailsPage',
    template: template,
    WHAT CODE TO RETRIEVE OPTIONS ?
});
```

/details-page/template.hbs : 
```
<document>
  <productTemplate>
    <banner>
      <stack>
        <title>WHAT CODE TO DISPLAY OPTIONS</title>
      </stack>
    </banner>
  </productTemplate>
</document>
```

Thanks.

**Comment by emadalam** [comment]
@procom Your use case is already covered here https://github.com/emadalam/atvjs#custom-options-while-navigation.

Example:

/details-page/index.js
```js
import template from './template.hbs';

ATV.Page.create({
	name: 'details-page',
	template: template,
	ready(options, resolve, reject) {
		// the options object has everything that you pass
		// options.title in your case
		// use it to do some custom operations and then resolve the promise with your final data
		// in your case, you can simply pass the entire options object as data
		resolve(options);
		// or you can fetch data through ajax based on your options
		// then resolve the promise with the provided data
	}
});
```
/details-page/template.hbs
```
<document>
  <productTemplate>
    <banner>
      <stack>
        <title>{{ title }}</title>
      </stack>
    </banner>
  </productTemplate>
</document>
```
Later in some other template you can simply use `<button data-href-page="details-page" data-href-page-options='{"title": "Hello World"}'>`  and atvjs will automatically bind the click handler at runtime to navigate to the `details-page`.

Let me know if this works, please close the issue if it does. Thanks!

**Comment by procom** [comment]
Thank you.
All works.
